Update buildspec.yml

diff --git a/buildspec.yml b/buildspec.yml
--- a/buildspec.yml
+++ b/buildspec.yml
@@ -48,11 +48,11 @@ phases:
   build:
     commands:
       - echo "Running unit tests with pytest..."
-      - python -m pytest test_app.py -v --cov=app --cov-report=xml
+      - python -m pytest --cov=app --cov-report=xml:coverage.xml test_app.py -v
       
       - echo "Running SonarCloud analysis..."
       - |
-        sonar-scanner -Dsonar.projectKey=$PROJECT_KEY -Dsonar.organization=$SONAR_ORG -Dsonar.sources=. -Dsonar.python.coverage.reportPaths=coverage.xml -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN -Dsonar.qualitygate.wait=true || echo "SONAR_FAILED=true" >> env_vars.txt
+        sonar-scanner -Dsonar.projectKey=$PROJECT_KEY -Dsonar.organization=$SONAR_ORG -Dsonar.sources=. -Dsonar.python.coverage.reportPaths=coverage.xml -Dsonar.tests=test_app.py -Dsonar.test.inclusions=test_app.py -Dsonar.python.xunit.reportPath=test-report.xml -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN -Dsonar.qualitygate.wait=true || echo "SONAR_FAILED=true" >> env_vars.txt
       - |
         if grep -q "SONAR_FAILED=true" env_vars.txt; then
           echo "❌ Sonar analysis failed. Logging to PostgreSQL and triggering Lambda..."
